### ISSUE TITLE
Handle ties appropriately

### ISSUE THREAD

**Issue by Undo1** [JC3/SOVoteMonitor#1]
When two candidates are tied during the primary, this happens:

![screen shot 2015-04-14 at 7 01 33 pm](https://cloud.githubusercontent.com/assets/5162342/7150483/b57f7de2-e2d8-11e4-990a-e2abd8981610.png)

I believe that the correct way of handling this would be to display _both_ users as being in 10th place, and move the red bar down.

**Comment by JC3** [comment]
It's irritating. However, I'm not going to fix this until I fix it _properly_; the most important open issue being where to place the red line if there's a tie in 10 or 11, and who to place in 10. I want the cutoff line to be accurate, so I want to use the same logic SE would use for breaking the tie. However, nobody really know what the criteria are: http://chat.stackoverflow.com/transcript/74583?m=22711594#22711594 

I may do something yet, but for now I'm not touching it until the correct solution is known.
