### ISSUE TITLE
serif font

### ISSUE THREAD

**Issue by MosheBerman** [JC3/SOVoteMonitor#3]
The serif font is really bothering me for some reason. I hate to be that guy but would you please consider using a sans-serif? Helvetia and Avenir are both nice.

**Comment by JC3** [comment]
On the right side towards the bottom, there is a link with "Themes". If you click "SO", that one has a sans-serif font. How does that look?

**Comment by MosheBerman** [comment]
Looks good! It would be fun to style this page more. :smile:
